name: CD - Deploy Backend Account Service (Triggered)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit SHA tag for image versioning'
        required: true

jobs:
  deploy:
    name: Build and Push Container
    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/account-service
      IMAGE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -f backend/account-service/Dockerfile \
            .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
