name: CI - Backend (Account Service)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch all history for Nx affected commands
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm dependencies
        run: pnpm install

      # Determine affected projects
      - name: Set up NX Base and Head SHAs
        uses: nrwl/nx-set-shas@v4

      # Lint affected projects
      - name: Run Affected Lint
        # run: pnpm nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD
        run: pnpm nx run-many --target=lint --projects=account-service

      # Run unit tests for account-service
      - name: Run Affected Backend Tests
        # run: pnpm nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --projects=account-service
        run: pnpm nx run-many --target=test --projects=account-service

      # Build account-service
      - name: Build Affected Backend
        # run: pnpm nx affected --target=build --base=$NX_BASE --head=$NX_HEAD --projects=account-service
        run: pnpm nx run-many --target=build --projects=account-service